package br.com.caelum.estoque.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2016-07-18T16:01:36.138-03:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://ws.estoque.caelum.com.br/", name = "EstoqueWS")
@XmlSeeAlso({ObjectFactory.class})
public interface EstoqueWS {

    @WebMethod
    @Action(input = "http://ws.estoque.caelum.com.br/EstoqueWS/todosOsItensRequest", output = "http://ws.estoque.caelum.com.br/EstoqueWS/todosOsItensResponse")
    @RequestWrapper(localName = "todosOsItens", targetNamespace = "http://ws.estoque.caelum.com.br/", className = "br.com.caelum.estoque.ws.TodosOsItens")
    @ResponseWrapper(localName = "todosOsItensResponse", targetNamespace = "http://ws.estoque.caelum.com.br/", className = "br.com.caelum.estoque.ws.TodosOsItensResponse")
    @WebResult(name = "itens", targetNamespace = "")
    public br.com.caelum.estoque.ws.ListaItens todosOsItens();

    @WebMethod
    @Action(input = "http://ws.estoque.caelum.com.br/EstoqueWS/todosOsItens2Request", output = "http://ws.estoque.caelum.com.br/EstoqueWS/todosOsItens2Response")
    @RequestWrapper(localName = "todosOsItens2", targetNamespace = "http://ws.estoque.caelum.com.br/", className = "br.com.caelum.estoque.ws.TodosOsItens2")
    @ResponseWrapper(localName = "todosOsItens2Response", targetNamespace = "http://ws.estoque.caelum.com.br/", className = "br.com.caelum.estoque.ws.TodosOsItens2Response")
    @WebResult(name = "itens2", targetNamespace = "")
    public br.com.caelum.estoque.ws.ListaItens todosOsItens2(
        @WebParam(name = "filtros", targetNamespace = "")
        br.com.caelum.estoque.ws.Filtros filtros
    );

    @WebMethod(operationName = "CadastrarItem")
    @Action(input = "http://ws.estoque.caelum.com.br/EstoqueWS/CadastrarItemRequest", output = "http://ws.estoque.caelum.com.br/EstoqueWS/CadastrarItemResponse", fault = {@FaultAction(className = AutorizacaoException.class, value = "http://ws.estoque.caelum.com.br/EstoqueWS/CadastrarItem/Fault/AutorizacaoException")})
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "CadastrarItemResponse", targetNamespace = "http://ws.estoque.caelum.com.br/", partName = "result")
    public CadastrarItemResponse cadastrarItem(
        @WebParam(partName = "parameters", name = "CadastrarItem", targetNamespace = "http://ws.estoque.caelum.com.br/")
        CadastrarItem parameters,
        @WebParam(partName = "token", name = "token", targetNamespace = "http://ws.estoque.caelum.com.br/", header = true)
        TokenUsuario token
    ) throws AutorizacaoException;

    @WebMethod
    @Action(input = "http://ws.estoque.caelum.com.br/EstoqueWS/todosOsItens3Request", output = "http://ws.estoque.caelum.com.br/EstoqueWS/todosOsItens3Response")
    @RequestWrapper(localName = "todosOsItens3", targetNamespace = "http://ws.estoque.caelum.com.br/", className = "br.com.caelum.estoque.ws.TodosOsItens3")
    @ResponseWrapper(localName = "itens", targetNamespace = "http://ws.estoque.caelum.com.br/", className = "br.com.caelum.estoque.ws.Itens")
    @WebResult(name = "itens", targetNamespace = "")
    public java.util.List<br.com.caelum.estoque.ws.Item> todosOsItens3();
}
